### ISSUE TITLE
GET KID API + epost + frontend

### ISSUE THREAD

**Issue by Mofoss** [stiftelsen-effekt/effekt-backend#106]
Lage et API eller annen funksjonalitet for at man på gieffektivt.no skal kunne taste inn epostadressen sin og få tilsendt en epost med alle sine eksisterende KID-nummer (fra databasen) med tilknyttet fordeling.  

Vi kan nok gjenbruke en del kode som finnes allerede (sjekke om brukeren finnes i databasen, samt utsending av epost med generert KID). 

(Inkluderer altså litt frontend også)

**Comment by fellmirr** [comment]
Most of the information donors might want should no be available on the profile page :+1:
