### ISSUE TITLE
[BackEnd] Skrive om til TypeScript

### ISSUE THREAD

**Issue by philiphand** [stiftelsen-effekt/effekt-backend#165]
Kilde til småfeil og irritasjon nå.
Krever tilsvarende ~en uke arbeid for Håkon.

Må først lage et transileringssteg, men det er en engangsinvestering og lar seg gjøre ganske lett.

**Comment by fellmirr** [comment]
This issue is about breaking down the work to rewriting the api to ts.

Make smaller issues for individual files / areas.

**Comment by fellmirr** [comment]
Oh, and the transpiling and setup step is already done.
