### ISSUE TITLE
Mail til faste donorer uten avtalegiro

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/effekt-backend#235]
- [x] Lage oversikt (database view) over faste donorer Bank U/KID
- [x] Lage tabell for å lagre om det er sendt ut avtalegiromail (og hvor mange, og når siste)
- [x] Lage funksjon som sjekker om identifisert fast giver alt har avtalegiro med gitt fordeling
- [x] Lage funksjon for å kopiere fordeling til ny KID med ny KID struktur
- [ ] Lage route som går igjennom faste givere med < n påminnelser, og kaller epostmalen
- [ ] Lage epostmal for avtalegiro-inngåelse

**Comment by karirk** [comment]
Har gitt Ruth beskjed om å legge i sin Asana
