### ISSUE TITLE
[AvtaleGiro] Sett standardbeskrivelse på betalinger slik det dukker opp i nettbanken til donor.

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/effekt-backend#243]
I nettbanken får donor opp en lang rekke 0 og 1-ere der det vanligvis er en beskrivelse av hva betalingen gjelder. Denne beskrivelsen kan vi nok bestemme på en eller annen måte. Finn ut av det i dokumentasjonen til AvtaleGiro og sett en passende beskrivelse.

**Comment by fellmirr** [comment]
Use fremmedreferanse felt to indicate `Donasjon til Gi Effektivt`, instead of blank spaces.

**Comment by EliseAndresen** [comment]
Har satt opp en avtalegiro for å sjekke, aktiveres 11.09.22
