### ISSUE TITLE
Importere donasjonsdata til databasen

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-backend#244]
Eldre vipps- og bankdonasjoner og alle Facebookdonasjoner, samt lage en permanent løsning for Facebook-donasjoner. Se instruksjoner i Slack-tråd: https://effektteam.slack.com/archives/G011BE3BG3H/p1624533457067600

**Comment by fellmirr** [comment]
Most is done, #364 is specific for facebook
