### ISSUE TITLE
☆☆☆ [AvtaleGiro] Lag epost og sett opp automatisk utsending av en bekreftelse til donorer når ny AG-avtale er aktivert på dem

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-backend#257]
Må ha med ordlyd som dekker:
* Navn på donor
* Bekreftelse på at AG-avtale er opprettet med oss
* Valgt sum og trekkdag
* Valgt fordeling på donasjonen
* [viktig å fremheve] Ønsker de å foreta noen endringer bør de sende oss en mail til donasjon@gieffektivt.no. Sletting eller endring av AG-avtalen i nettbanken er ikke garantert å stoppe trekk fra oss om det er nært trekkdagen.

* Standardtekst om skattefradrag
* 100% av pengene går dit de har valgt
* Standard hilsen, header og footer

**Comment by fellmirr** [comment]
Should include text about min side to change agreements *not* info about contacting us on email

**Comment by EliseAndresen** [comment]
Started: #257-email-when-registered-ag
