### ISSUE TITLE
[Epost-kvitteringer] Fjern setningen om gjenbruk av KID for betalingstyper hvor det ikke er aktuelt

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-backend#301]
Det gjelder setningen "Hvis du ønsker å donere med samme fordeling senere kan du bruke samme KID-nummer igjen. Du står helt fritt til å endre beløpet du donerer."

Dette er bare relevant for giveren om de manuelt har måttet forholde seg til KID-nummeret. Det gjelder kun enkeltdonasjoner via Bank (ikke AvtaleGiro) såvidt jeg kan komme på nå.

Endre epostmalen slik at denne setningen kun vises på kvitteringer som er for enkeltdonasjoner via Bank.

**Comment by fellmirr** [comment]
You may reuse the KID for avtalegiro as a single bank donation, as far as I know. Wether it is relevant for AvtaleGiro customers is perhaps another matter, but I don't find it entirely implausible that some might want to reuse the same KID for a single donation (I believe we have seen instances of this in practice).
