### ISSUE TITLE
[Database] Make changes in "Organizations" table name and abbreviations

### ISSUE THREAD

**Issue by philiphand** [stiftelsen-effekt/effekt-backend#308]
- [ ] Set "Drift av gieffektivt.no" to ID = 0 and those with ID larger than 11 back one number
- [ ] Change the following spellings of names:
> - Schistosomiasis Control Initiative -> SCI Foundation
> - The End Fund -> The END Fund
> - Project Healthy Children -> Sanku - Project Healthy Children
> - Hellen Keller International -> Helen Keller International
> - Drift av gieffektivt.no -> Drift av Gi Effektivt
> - GiveWells tildelingsfond -> GiveWell Maximum Impact Fund
- [ ] Change the following spellings of abbreviations:
> - End -> END
> - Sight -> SS
> - GiveWell -> MIF

**Comment by JorgenLjones** [comment]
If changing the ID will break a lot of other stuff, then we shouldn't do it of course, but it would be nice to tidy this up
