### ISSUE TITLE
Expand AG change notification email

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-backend#390]
This is the current layout:
![Image](https://user-images.githubusercontent.com/12774906/183039012-a5a09c5d-6dcb-4d02-8120-597ee0607a93.png)

Add an overview section of their AG below the line that explains what changed for convenience:
- [ ] "Din oppdaterte AvtaleGiro:"
- [ ] Sum
- [ ] Charge day
- [ ] Distribution
- [ ] Notify on or off

**Comment by EliseAndresen** [comment]
Tacked in #733
