### ISSUE TITLE
☆☆☆ Email SPF setup incorrect

### ISSUE THREAD

**Issue by EliseAndresen** [stiftelsen-effekt/effekt-backend#433]
Hei!

Eg får alltid varsel på e-postane frå dykk om at e-postautentiseringa ikkje er sett riktig opp, og kan vere farlege. Så eg tenkte berre å informere om det, og korleis det går an å løyse!

Grunnen til at dette skjer er at det som heiter SPF ikkje er riktig. Dette er ein DNS-record som seier kven som kan sende e-post frå gieffektiv.no-domenet. Berre e-post frå [domeneshop.no](http://domeneshop.no/) er tillatt (`v=spf1 include:_[spf.domeneshop.no](http://spf.domeneshop.no/) ~all`).
Men det ser ut som at desse kvitterings-e-postane er sendt med Mailgun. Derfor må Mailgun sine serverar/IP-adresser også vere godkjent. Mailgun har ein artikkel om dette her: https://www.mailgun.com/blog/deliverability/spf-records-basics/

Eg trur det riktige for dykk er å få endra `v=spf1 include:_[spf.domeneshop.no](http://spf.domeneshop.no/) ~all` til ``v=spf1 include:[mailgun.org](http://mailgun.org/) include:_[spf.domeneshop.no](http://spf.domeneshop.no/) ~all`

Eg kan òg anbefale å sjekke ut denne monitorerings-tenesta (gratis) for å få vekentlege oppdateringar på at e-postutsending er sett opp riktig: https://dmarc.postmarkapp.com/

**Comment by JorgenLjones** [comment]
Donor er ventet å få ny donasjonskvittering mandag 10. oktober. Vi bør følge opp donor etter dette for å høre om det fikset seg nå
