### ISSUE TITLE
Fix thousands delimiter in donation notification email

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/effekt-backend#446]
In Norwegian we use space as thousands delimiter, and comma as decimal sign

**Comment by JorgenLjones** [comment]
![Image](https://user-images.githubusercontent.com/12774906/199681997-22d21f2d-5959-4b3a-a854-38b1e9372982.png)

**Comment by fellmirr** [comment]
Ooof, this is a regex bug guaranteed. Kind of nasty this one.

**Comment by JorgenLjones** [comment]
As in will take a long time to fix?


*Jørgen Ljønes *|* Daglig leder*

Tel: +47 47852177 <+4747852177>

Gi Effektivt <http://www.gieffektivt.no/>
