### ISSUE TITLE
Database error: This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration

### ISSUE THREAD

**Issue by adamalfredsson** [stiftelsen-effekt/effekt-backend#566]
When running migrations on my local database via `npx prisma migrate reset`, I get this error:

> Applying migration `01_functions`
> Error: P3018
> 
> A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
> 
> Migration name: 01_functions
> 
> Database error code: 1418
> 
> Database error:
> This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)
> 
> Please check the query number 11 from the migration file.

I'm fairly certain this led me to [this SO answer](https://stackoverflow.com/a/26015334/7776268) where I was prompted to add this to the top of `01_functions.sql` migration:

```sql
SET GLOBAL log_bin_trust_function_creators = 1;
```

**Comment by lorentzlasson** [comment]
Interesting. I played around with it as well, but I get a similar error still when converting to deterministic/read only etc. Perhaps it's function specific

```sql
:GeEffektivtDev>
 CREATE FUNCTION `check_all_donations_sumto_100`()
> RETURNS tinyint(1)
> READS SQL DATA
> DETERMINISTIC
> BEGIN if (
>   COUNT(get_sum_of_donation_KIDs_not_totaling_100() > 0)
> ) then return 0;
>
> else return 1;
>
> end if;
>
> END;
(1419, 'You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)')
```

**Comment by hakon55** [comment]
Weird, when i ran with:
```sql 
CREATE FUNCTION `check_all_donations_sumto_100`() RETURNS tinyint(1) READ SQL DATA DETERMINISTIC BEGIN if (
  COUNT(get_sum_of_donation_KIDs_not_totaling_100() > 0)
) then return 0;
```

I got the Database error code: 1064.

However, when changing the order of "READ SQL DATA" and "DETERMINISTIC", it worked. 
```sql 
CREATE FUNCTION `check_all_donations_sumto_100`() RETURNS tinyint(1)  DETERMINISTIC READ SQL DATA BEGIN if
```

Don't know how the function signature works with SQL, if the precedence invalidates the other.

**Comment by fellmirr** [comment]
@adamalfredsson Not an issue anymore, right?

**Comment by adamalfredsson** [comment]
That's right, if you run MySQL via docker-compose as recommended this should not be an issue.
