### ISSUE TITLE
Registrering av donasjoner som ikke har KID

### ISSUE THREAD

**Issue by AndreasII** [stiftelsen-effekt/effekt-backend#84]
Burde vi beholde donorinfo og lage nye bruker for donorer som donerer uten å ha registrert seg?

Gjelder potensielt Vipps og bank.

**Comment by fellmirr** [comment]
Potensielt endre oppførsel på registrering av vipps u / KID, @JorgenLjones holder i det.

Kan også gjøre retroaktive endringer her, men mye styr.
